### ISSUE TITLE
"server shut down"

### ISSUE THREAD

**Issue by no-wherenear** [maxiz1225/the-simple-unblocker-public#4]
Basically a lot of times (90% of the time) i go to "the simple unblocker" some thingy pops out saying error 521 that servers shut down and it wouldn't let me go into the page, kinda frustrating to wait hours till its back up just for it to shut down a few minutes later.

**Comment by no-wherenear** [comment]
it may only be me :/

**Comment by maxiz1225** [comment]
yeah it happens sometimes and during march it was the worst of it i fixed the issue mostly and it runs much more stable server side
